"""update customer_regex_rule table

Revision ID: 72ddc312e95a
Revises: 7405c6dbf790
Create Date: 2025-12-26 17:57:00.287034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72ddc312e95a'
down_revision: Union[str, None] = '7405c6dbf790'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_regex_rule', sa.Column('group', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_regex_rule', 'group')
    # ### end Alembic commands ###
