"""create customer_regex_rule table

Revision ID: 7405c6dbf790
Revises: e3e46b0532ec
Create Date: 2025-12-26 16:48:12.946530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7405c6dbf790'
down_revision: Union[str, None] = 'e3e46b0532ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_regex_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('pattern', sa.String(), nullable=True),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_regex_rule_customer_id'), 'customer_regex_rule', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_regex_rule_id'), 'customer_regex_rule', ['id'], unique=False)
    op.create_index(op.f('ix_customer_regex_rule_pattern'), 'customer_regex_rule', ['pattern'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_regex_rule_pattern'), table_name='customer_regex_rule')
    op.drop_index(op.f('ix_customer_regex_rule_id'), table_name='customer_regex_rule')
    op.drop_index(op.f('ix_customer_regex_rule_customer_id'), table_name='customer_regex_rule')
    op.drop_table('customer_regex_rule')
    # ### end Alembic commands ###
